plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
}

android {
    namespace 'com.melonhead.lib_logging'
}

dependencies {
    // Import the BoM for the Firebase platform
    implementation libs.bundles.ktor
    implementation platform(libs.firebase.bom)
    implementation libs.bundles.firebase

    implementation libs.bundles.common
    testImplementation libs.bundles.common.test
    androidTestImplementation libs.bundles.common.android.test
}

apply from: "$rootProject.projectDir/android-module.gradle"