plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
    alias libs.plugins.compose.plugin
}

android {
    namespace 'com.melonhead.lib_navigation'
}

dependencies {
    implementation libs.bundles.common
    testImplementation libs.bundles.common.test
    implementation libs.bundles.koin
}

apply from: "$rootProject.projectDir/compose-module.gradle"