plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
    alias libs.plugins.kotlinx.serialization
}

android {
    namespace 'com.melonhead.lib_authentication'
}

dependencies {
    implementation libs.bundles.common
    testImplementation libs.bundles.common.test
    implementation project(':lib-app-data')
    implementation project(":lib-networking")
    implementation project(":lib-logging")
}

apply from: "$rootProject.projectDir/android-module.gradle"
