plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlinx.serialization)
}

android {
    namespace 'com.melonhead.data_manga'
}

dependencies {
    implementation libs.bundles.common
    testImplementation libs.bundles.common.test
    implementation libs.bundles.koin
    implementation libs.bundles.ktor

    implementation project(":lib-logging")
    implementation project(":lib-networking")
    implementation project(':lib-app-data')
    implementation project(':data-shared')
}

apply from: "$rootProject.projectDir/android-module.gradle"
