plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
    alias libs.plugins.kotlinx.serialization
}

android {
    namespace 'com.melonhead.network_at_home'
}

dependencies {
    implementation libs.bundles.common
    testImplementation libs.bundles.common.test

    implementation project(":lib-networking")
    implementation project(":lib-logging")
    implementation project(':lib-app-data')
}

apply from: "$rootProject.projectDir/android-module.gradle"
