plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
}

android {
    namespace 'com.melonhead.lib_app_events'
}

dependencies {
    implementation libs.bundles.common
    testImplementation libs.bundles.common.test
    implementation libs.bundles.koin

    implementation project(":lib-logging")
    implementation project(':data-shared')
}

apply from: "$rootProject.projectDir/android-module.gradle"