plugins {
    alias libs.plugins.android.application
    alias libs.plugins.kotlin.android    
    alias libs.plugins.kotlinx.serialization
    alias libs.plugins.compose.plugin
    alias libs.plugins.google.services
    alias libs.plugins.firebase.crashlytics
    id 'kotlin-parcelize'
}

android {
    namespace 'com.melonhead.mangadexfollower'

    defaultConfig {
        applicationId "com.melonhead.mangadexfollower"

        versionCode 38
        versionName "1." + versionCode

        vectorDrawables {
            useSupportLibrary true
        }
    }

    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

apply from: "$rootProject.projectDir/compose-module.gradle"

tasks.register('generateVersionTxt') {
    doLast {
        file("./version.txt").text = android.defaultConfig.versionName + "." + android.defaultConfig.versionCode
    }
}

dependencies {
    implementation libs.bundles.common
    testImplementation libs.bundles.common.test
    implementation libs.work.ktx
    implementation libs.bundles.koin

    // note: this should not contain any dependencies on ':data-X' modules, those should only be used by features

    implementation project(':lib-core')
    implementation project(":lib-app-events")
    implementation project(":lib-logging")
    implementation project(":lib-notifications")
    implementation project(":lib-navigation")
    implementation project(":lib-database")
    implementation project(":lib-app-context")
    implementation project(':lib-chapter-cache')
    implementation project(":lib-networking")

    implementation project(':feature-authentication')
    implementation project(':feature-manga-list')
    implementation project(':feature-native-chapter-viewer')
    implementation project(':feature-webview-chapter-viewer')
}
