plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
    alias libs.plugins.kotlinx.serialization
    alias libs.plugins.compose.plugin
}

android {
    namespace 'com.melonhead.lib_app_data'
}

dependencies {

    implementation libs.bundles.common
    testImplementation libs.bundles.common.test
    implementation libs.datastore.preferences
    implementation libs.bundles.koin

    implementation project(":lib-logging")
    implementation project(":lib-database")
}

apply from: "$rootProject.projectDir/android-module.gradle"