plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
}

android {
    namespace 'com.melonhead.data_user'
}

dependencies {
    implementation libs.bundles.common
    testImplementation libs.bundles.common.test

    implementation project(":lib-networking")
    implementation project(":lib-logging")
    implementation project(':lib-app-data')
    implementation project(':data-shared')
}

apply from: "$rootProject.projectDir/android-module.gradle"