plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
}

android {
    namespace 'com.melonhead.lib_app_context'
}

dependencies {
    implementation libs.bundles.common
    testImplementation libs.bundles.common.test
    implementation libs.bundles.koin
}

apply from: "$rootProject.projectDir/android-module.gradle"