plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
    alias libs.plugins.compose.plugin
}

android {
    namespace 'com.melonhead.feature_native_chapter_viewer'
    compileSdk 34

    defaultConfig {
        minSdk 24

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }
    buildFeatures {
        compose true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation libs.bundles.common
    testImplementation libs.bundles.common.test
    implementation libs.bundles.koin

    implementation project(':lib-core')
    implementation project(":lib-app-events")
    implementation project(":lib-logging")
    implementation project(":lib-navigation")
    implementation project(":lib-chapter-cache")
    implementation project(':lib-app-data')

    implementation project(':data-shared')

    api project(':lib-app-data')

}
