plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
}

android {
    namespace 'com.melonhead.lib_read_status'
}

dependencies {
    implementation libs.bundles.common
    testImplementation libs.bundles.common.test
    implementation libs.bundles.koin

    implementation project(":lib-database")
    implementation project(":lib-logging")
    implementation project(":lib-networking")
}

apply from: "$rootProject.projectDir/android-module.gradle"