plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
    alias libs.plugins.compose.plugin
    id 'kotlin-parcelize'
}

android {
    namespace 'com.melonhead.lib_core'
}

dependencies {
    implementation libs.bundles.compose
    debugImplementation libs.bundles.compose.debug

    implementation libs.bundles.common
    testImplementation libs.bundles.common.test

    implementation project(":data-shared")

    api libs.bundles.compose
    debugApi libs.bundles.compose.debug
}

apply from: "$rootProject.projectDir/compose-module.gradle"