plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
    alias libs.plugins.kotlinx.serialization
    alias libs.plugins.compose.plugin
}

android {
    namespace 'com.melonhead.data_manga'
    compileSdk 34

    defaultConfig {
        minSdk 24

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        compose true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation libs.bundles.common
    testImplementation libs.bundles.common.test
    implementation libs.accompanist.swiperefresh
    implementation libs.bundles.koin

    implementation project(':lib-core')
    implementation project(":lib-app-context")
    implementation project(":lib-networking")
    implementation project(":lib-logging")
    implementation project(":lib-database")
    implementation project(":lib-notifications")
    implementation project(":lib-app-events")
    implementation project(':lib-chapter-cache')
    implementation project(':lib-navigation')
    implementation project(':lib-app-data')
    implementation project(':data-shared')
    implementation project(":data-user")
    implementation project(":data-at-home")
    implementation project(":data-manga")
    implementation project(":data-rating")
    api project(':data-shared')

    api project(":data-manga")
    api project(':lib-app-data')
}
