plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
    alias libs.plugins.kotlinx.serialization
    alias libs.plugins.compose.plugin
}

android {
    namespace 'com.melonhead.feature_authentication'

    def properties = new Properties()
    if (rootProject.file("local.properties").exists()) {
        properties.load(rootProject.file("local.properties").newDataInputStream())
    }

    def debugEmail = properties.getProperty("debug_email", "")
    def debugPassword = properties.getProperty("debug_password", "")
    def debugClientId = properties.getProperty("debug_client_id", "")
    def debugClientSecret = properties.getProperty("debug_client_secret", "")

    defaultConfig {
        buildConfigField("String", "DEBUG_EMAIL", "\"${debugEmail}\"")
        buildConfigField("String", "DEBUG_PASSWORD", "\"${debugPassword}\"")
        buildConfigField("String", "DEBUG_CLIENT_ID", "\"${debugClientId}\"")
        buildConfigField("String", "DEBUG_CLIENT_SECRET", "\"${debugClientSecret}\"")
    }
}

dependencies {
    implementation libs.bundles.common
    testImplementation libs.bundles.common.test
    implementation project(':lib-core')
    implementation project(":lib-networking")
    implementation project(":lib-logging")
    implementation project(":lib-notifications")
    implementation project(":lib-navigation")
    implementation project(":lib-app-context")
    implementation project(":lib-app-events")
    implementation project(':lib-app-data')
    implementation project(":data-user")
    implementation project(":data-authentication")
    api project(':lib-app-data')

}

apply from: "$rootProject.projectDir/compose-module.gradle"
