plugins {
    alias libs.plugins.android.library
    alias libs.plugins.kotlin.android
    alias libs.plugins.kotlinx.serialization
    id 'kotlin-parcelize'
}

android {
    namespace 'com.melonhead.data_shared'
}

dependencies {
    implementation libs.bundles.ktor
    implementation libs.bundles.common
    testImplementation libs.bundles.common.test
}

apply from: "$rootProject.projectDir/android-module.gradle"