name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        signingKeyBase64: ${{ secrets.DEBUG_KEYSTORE_BASE64 }}
        # The key alias
        alias: ${{ secrets.DEBUG_KEYSTORE_ALIAS }}
        # The password to the keystore
        keyStorePassword: ${{ secrets.DEBUG_KEYSTORE_PASSWORD }}
      run: |
        echo "KEY"
        echo $signingKeyBase64 | sed 's/./& /g'
        
        echo "ALIAS"
        echo $alias | sed 's/./& /g'

        echo "PASS"
        echo $keyStorePassword | sed 's/./& /g'
